name: SlimePlugin
version: ${project.version}

author: Phoenix
website: https://github.com/PhoenixCodingStuff/SlimePlugin
description: A Minecraft plugin template for SlimeCraftSMP plugins.

main: me.phoenix.slimeplugin.SlimePlugin
api-version: 1.20
depend: [Slimefun, SlimeLib]
