name: End to End Testing

on:
  workflow_call:
    inputs:
      artifact-name:
        description: 'SlimePlugin artifact name'
        required: true
        type: string

jobs:
  e2e-testing:
    name: End to End Testing
    runs-on: ubuntu-latest
    timeout-minutes: 3

    strategy:
      matrix:
        include:
          - mcVersion: '1.20.4'
            javaVersion: '21'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Set up JDK 21
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'adopt'
          java-version: '21'
          java-package: jdk
          architecture: x64

      - name: Setup server
        run: |
          echo 'eula=true' > eula.txt
          mkdir plugins

      - name: Download ${{ matrix.mcVersion }} Paper
        run: |
          VERSION="${{ matrix.mcVersion }}"
          if [ "$VERSION" == "latest" ]; then
            VERSION=$(curl https://api.papermc.io/v2/projects/paper/ -s | jq -r '.versions[-1]')
          fi

          BUILD_JAR=$(curl -s "https://api.papermc.io/v2/projects/paper/versions/$VERSION/builds" \
            | jq '.builds[-1] | "\(.build) \(.downloads.application.name)"' -r)
          BUILD=$(echo "$BUILD_JAR" | awk '{print $1}')
          JAR_FILE=$(echo "$BUILD_JAR" | awk '{print $2}')

          echo "Downloading... https://api.papermc.io/v2/projects/paper/versions/$VERSION/builds/$BUILD/downloads/$JAR_FILE"
          curl -o paper.jar \
            "https://api.papermc.io/v2/projects/paper/versions/$VERSION/builds/$BUILD/downloads/$JAR_FILE"

      - name: Download Slimefun
        run: |
          RELEASE=$(curl -s https://api.github.com/repos/SlimeCraftSMP/Slimefun4/releases/latest | jq -r '.assets[0].browser_download_url')
          curl -L -o Slimefun4-SlimeCraftSMP.jar "$RELEASE"
          mv Slimefun4-SlimeCraftSMP.jar plugins/Slimefun4-SlimeCraftSMP.jar

      - name: Download SlimeLib
        run: |
          RELEASE=$(curl -s https://api.github.com/repos/SlimeCraftSMP/SlimeLib/releases/latest | jq -r '.assets[0].browser_download_url')
          curl -L -o SlimeLib.jar "$RELEASE"
          mv SlimeLib.jar plugins/SlimeLib.jar

      - name: Download SlimePlugin
        uses: actions/download-artifact@v4.1.7
        with:
          name: ${{ inputs.artifact-name }}
          path: plugins/

      - name: Run server
        run: |
          java -jar paper.jar --nogui &
          sleep 60
          kill $!
          exit 0
