name: Validate JSON

on:
  push:
    branches:
    - main
    paths:
    - 'src/main/resources/wiki.json'
  pull_request:
    branches:
    - main
    paths:
    - 'src/main/resources/wiki.json'

permissions:
  contents: read

jobs:
  validate:

    name: Validate JSON
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4.1.1
    - name: Validate wiki.json
      uses: docker://orrosenblatt/validate-json-action:latest
      env:
        INPUT_SCHEMA: '.github/configs/wiki-schema.json'
        INPUT_JSONS: 'src/main/resources/wiki.json'
