name: Java CI

on:
  push:
    branches:
    - main
    paths:
    - 'src/**'
    - 'pom.xml'
  pull_request:
    branches:
    - main
    paths:
    - 'src/**'
    - 'pom.xml'

permissions:
  contents: read

jobs:
  build:
    if: startsWith(github.event.head_commit.message, '[Skip]') == false

    name: Maven build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1

    - name: Set up JDK 21
      uses: actions/setup-java@v4.2.1
      with:
        distribution: 'adopt'
        java-version: '21'
        java-package: jdk
        architecture: x64

    - name: Cache Maven packages
      uses: actions/cache@v4.0.2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - id: env-setup
      run: |
        sed -i "s/<version>UNOFFICIAL<\/version>/<version>${{ github.run_number }}<\/version>/g" pom.xml

    - name: Build with Maven
      run: mvn package

    - name: Upload the artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: slimeplugin-${{ github.run_number }}
        path: 'target/SlimePlugin v${{ github.run_number }}.jar'

  test-build:
    needs: [build]
    uses: ./.github/workflows/e2e-testing.yml
    with:
      artifact-name: slimeplugin-${{ github.run_number }}

  release-build:
    if: startsWith(github.event.head_commit.message, '[Release]') == true
    needs: [test-build]
    uses: ./.github/workflows/release.yml
    with:
      artifact-name: slimeplugin-${{ github.run_number }}
    secrets:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
