name: YAML Linter

on:
  push:
    branches:
    - main
    paths:
    - '**.yml'
  pull_request:
    branches:
    - main
    paths:
    - '**.yml'

permissions:
  contents: read

jobs:
  linter:

    name: YAML Linter
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1
    - name: YAML Linter
      uses: ibiqlik/action-yamllint@v3.1.1
      with:
        config_file: '.github/configs/yaml-linter.yml'
